repos:
-   repo: local
    hooks:
    - id: rustfmt
      name: Rust Format
      entry: cargo +nightly fmt --
      language: system
      types: [rust]
    - id: rust-check
      name: Rust Check
      entry: cargo check
      language: system
      types: [rust]
      pass_filenames: false
    - id: rust-test
      name: Rust Tests
      entry: cargo test
      language: system
      types: [rust]
      pass_filenames: false
