name: Lint and Test
run-name: Linting and Testing by ${{ github.actor }}

on:
  push:
    paths: ["src/**", crates/**, "Cargo.toml", ".pre-commit-config.yaml"]
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ runner.os }}-pre-commit-

      - name: Install rust toolchain
        run: |
          rustup update nightly
          rustup component add rustfmt --toolchain nightly

      - name: Run pre-commit
        run: pre-commit run --all-files
